language: php
php:
  - 5.4
  - 5.5
  - hhvm
install:
  - composer install

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover